kind: Secret
apiVersion: v1
metadata:
  name: scfhq-cross-mgateway-fra
  namespace: develop
data:
  KID: ZGV2X2Nyb3NzX21nX2Zy
  KEY: Y25GNFUyazNaMFpoWm01MFMxZ3dTWEkzWmtFMFJqTjVhbEZUYUVKaWIySmxTekkyWWpSWVdHdGhXV3RGVTJ0SmEwVmFaSFJFTTJWdFlqTndhbkpuYzBVeU56ZG9ia1JyUmxsYWRqVnZVRXhYVTNJeGVtYzFjbU5CWW1sSFRsTXphMWRZZERSaGFqVkxhSFZ4TWpaTFZsTlNXRzg0Yld4aldtUjVXbVZtTTFnPQ==
  URL: aHR0cHM6Ly9hcGlzLmRldi5zYW50YW5kZXJjb25zdW1lci5jb20vaHEvZ2xvYmFsY3Jvc3MvY29uZmlndXJhdGlvbi8xLjA=
  APPID: ODI3ZjIwMjItMTVkNy00ZTU3LWEzMGEtZmYyMmY4MWE3Yzk0
  OAuthSERVER: aHR0cHM6Ly9hcGlzLmRldi5zYW50YW5kZXJjb25zdW1lci5jb20vb2F1dGgycHJvdmlkZXJnbG9iYWxjcm9zcy9vYXV0aDIvdG9rZW4=
  OAuthID: YTQyYzdiNzYtMjg3My00MTNmLTgzMjItYmVhOWM0NTU3Yzgw
  OAuthSECRET: WTBtSzNwRjFvSTdoVjJhQjJoTDBmTDRmWThwRjBlQTNxTzNsRDdxTDB3UjdnVDVzVDI=
  OAuthSCOPE: Y2F0YWxvZy5hbGw=
type: Opaque
